# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}

# Hibernate
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

# JWT
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=https://unify.com.br
smallrye.jwt.sign.key.location=privateKey.pem
smallrye.jwt.new-token.lifespan=3600
smallrye.jwt.new-token.issuer=https://unify.com.br

# Token config
unify.jwt.access-token.expiration-minutes=60
unify.jwt.refresh-token.expiration-days=30

# Mailtrap / Mailer config
quarkus.mailer.host=${MAILTRAP_HOST:smtp.mailtrap.io}
quarkus.mailer.port=${MAILTRAP_PORT:587}
quarkus.mailer.username=${MAILTRAP_USERNAME:your_mailtrap_username}
quarkus.mailer.password=${MAILTRAP_PASSWORD:your_mailtrap_password}
quarkus.mailer.from=${MAILTRAP_FROM:no-reply@unify.local}

# Email verification config
unify.mail.verification.expiration-hours=3

%test.quarkus.mailer.mock=true
