-- Unify API initial schema seed
-- Tables are auto-generated by Hibernate (drop-and-create)
-- Add seed data below as needed

create unique index if not exists uq_user_coordinates_active_profile
    on user_coordinates (fk_user_profile)
    where active = true;

create unique index if not exists uq_user_profile_images_active_profile_pic
    on user_profile_images (fk_user_profile)
    where active = true and is_profile_pic = true;

create index if not exists idx_user_profile_images_active_gallery
    on user_profile_images (fk_user_profile, id desc)
    where active = true and is_profile_pic = false;

insert into genders(id, description)
values (1, 'Mulher'),
       (2, 'Homem'),
       (3, 'Não binário'),
       (4, 'Prefiro não informar');

insert into pronouns(id, description)
values (1, 'Ela/Dela'),
       (2, 'Ele/Dele'),
       (3, 'Elu/Delu'),
       (4, 'Prefiro não informar');

insert into disabilities(id, description, ionic_icon)
values (1, 'Física', 'walk-outline'),
       (2, 'Visual', 'eye-outline'),
       (3, 'Auditiva', 'ear-outline'),
       (4, 'Intelectual', 'accessibility-outline');

insert into accessibility_needs(id, description)
values (1, 'Cadeira de rodas'),
       (2, 'Libras'),
       (3, 'Leitor de tela'),
       (4, 'Comunicação assistiva');

insert into autonomy_levels(id, description)
values (1, 'Independente'),
       (2, 'Parcialmente independente'),
       (3, 'Precisa de apoio');

insert into communication_forms(id, description)
values (1, 'Texto'),
       (2, 'Áudio'),
       (3, 'Vídeo'),
       (4, 'Libras'),
       (5, 'Comunicação assistiva');

insert into lifestyle_types(id, description)
values (1, 'Caseiro'),
       (2, 'Social'),
       (3, 'Gosta de viajar'),
       (4, 'Atividades acessíveis');

insert into love_languages(id, description)
values (1, 'Palavras de afirmação'),
       (2, 'Tempo de qualidade'),
       (3, 'Presentes'),
       (4, 'Atos de serviço'),
       (5, 'Toque físico');

insert into energy_levels(id, description)
values (1, 'Baixa'),
       (2, 'Moderada'),
       (3, 'Alta');

insert into interest_types(id, description)
values (1, 'Esportes adaptados'),
       (2, 'Cultura'),
       (3, 'Tecnologia'),
       (4, 'Jogos'),
       (5, 'Música'),
       (6, 'Filmes e séries');

insert into connection_types(id, description)
values (1, 'Amizade'),
       (2, 'Relacionamento'),
       (3, 'Networking'),
       (4, 'Comunidade');

insert into 
    users(id, verified, last_updated_at, birthdate, email, last_name, name, password)
    values ('019dbf9a-5a8e-72de-85cb-8426b424c6fe', true, '2024-06-01T00:00:00Z', '1995-04-15', 'teste@gmail.com', 'Ambiel', 'Pedro', '$2a$10$YaiH0J4eVMU6kjtG5pm.oeOxPRPCk1ZX.XjKrXZOqEdhQv1bbo8KG'),
    ('019dcfdc-fa72-722b-89ac-e331eb4f119a', false, '2024-06-01T00:00:00Z', '1998-11-08', 'verificar@gmail.com', 'Email', 'Verificar', '$2a$10$YaiH0J4eVMU6kjtG5pm.oeOxPRPCk1ZX.XjKrXZOqEdhQv1bbo8KG');